In [ ]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
import numpy as np
import matplotlib.pyplot as plt 
import pandas as pd


In [93]:
#LDA in iris data set 

from sklearn import datasets 
from sklearn.preprocessing import LabelEncoder
iris_data = datasets.load_iris(as_frame=True)
X = pd.DataFrame(iris_data.data,columns=iris_data.feature_names)
Y = pd.Categorical.from_codes(iris_data.target, iris_data.target_names)
#Y = iris_data.target
data = X.join(pd.Series(Y,name='target'))

In [94]:
#Compute mean vector for each class labels 

class_feature_means = pd.DataFrame(columns=[0,1,2])
for c, rows in data.groupby('target'):
    class_feature_means[c] = rows.mean()
class_feature_means   

0    1    2  setosa  versicolor  virginica
sepal length (cm)  NaN  NaN  NaN   5.006       5.936      6.588
sepal width (cm)   NaN  NaN  NaN   3.428       2.770      2.974
petal length (cm)  NaN  NaN  NaN   1.462       4.260      5.552
petal width (cm)   NaN  NaN  NaN   0.246       1.326      2.026

In [107]:
intra_class_scatter_matrix = np.zeros((4,4))
for c, rows in data.groupby('target'):
    rows = rows.drop(['target'], axis=1)
    s = np.zeros((4,4))
for index, row in rows.iterrows():
        x, mc = row.values.reshape(4,1), class_feature_means[c].values.reshape(4,1)    
        s += (x - mc).dot((x - mc).T)
        intra_class_scatter_matrix += s
print(intra_class_scatter_matrix)

[[19.8128  4.5944 14.8612  2.4056]
 [ 4.5944  5.0962  3.4976  2.3338]
 [14.8612  3.4976 14.9248  2.3924]
 [ 2.4056  2.3338  2.3924  3.6962]]


In [110]:
feature_means = data.mean()
between_class_scatter_matrix = np.zeros((4,4))
for c in class_feature_means:    
    n = len(data.loc[data['target'] == c].index)
    mc, m = class_feature_means[c].values.reshape(4,1), feature_means.values.reshape(4,1)
    between_class_scatter_matrix += n * (mc - m).dot((mc - m).T)

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('O') to dtype('float64') with casting rule 'same_kind'